teacher/blogs/urls.py
from django.urls import path
from .views import bl

app_name = 'blogs'

urlpatterns = [
    path('blogs/', bl, name='list')
]

teacher/config/urls.py
from django.contrib import admin
from django.urls import path, include
from article.views import index
from blogs.views import bl
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls', namespace='articles')),
    path('', include('blogs.urls', namespace='blogs')),
    path('account/', include('account.urls', namespace='account')),
    path('recipes/', include('recipes.urls', namespace='recipes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teacher/recipes/urls.py
from django.urls import path
from .views import recipe_list, recipe_detail, recipe_create, recipe_update, recipe_delete, tag_create, tag_detail
from .views import tag_delete, tag_update, tag_list, ing_create, ing_update, ing_delete, my_recipes

app_name = 'recipes'

urlpatterns = [
    path('list/', recipe_list, name='list'),
    path('my/list/', my_recipes, name='my_list'),
    path('detail/<slug:slug>/', recipe_detail, name='detail'),
    path('create/', recipe_create, name='create'),
    path('update/<slug:slug>/', recipe_update, name='update'),
    path('delete/<slug:slug>/', recipe_delete, name='delete'),

    path('tag/list/', tag_list, name='tag_list'),
    path('tag/detail/<int:pk>/', tag_detail, name='tag_detail'),
    path('tag/create/', tag_create, name='tag_create'),
    path('tag/update/<int:pk>/', tag_update, name='tag_update'),
    path('tag/delete/<int:pk>/', tag_delete, name='tag_delete'),

    path('<slug:recipe_slug>/ing/create/', ing_create, name='ing_create'),
    path('<slug:recipe_slug>/ing/update/<int:pk>/', ing_update, name='ing_update'),
    path('<slug:recipe_slug>/ing/delete/<int:pk>/', ing_delete, name='ing_delete'),
]

teacher/recipes/models.py
import random
import string

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.utils.text import slugify


class Tag(models.Model):
    title = models.CharField(max_length=221, unique=True)

    def __str__(self):
        return self.title


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=221, db_index=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    modified_date = models.DateTimeField(auto_now=True)
    created_date = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


class RecipeIngredient(models.Model):
    UNIT = (
        (0, 'GRAMM'),
        (1, 'MILLILITR'),
        (2, 'DONA'),
    )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')
    title = models.CharField(max_length=221)
    quantity = models.IntegerField()
    unit = models.IntegerField(choices=UNIT)
    modified_date = models.DateTimeField(auto_now=True)
    created_date = models.DateTimeField(auto_now_add=True)

    # def get_author(self):
    #     return self.recipe.author

    def __str__(self):
        return self.title


def recipe_post_save(sender, instance, created, *args, **kwargs):
    if created:
        if instance.slug is None:
            instance.slug = slugify(instance.title)
            try:
                instance.save()
            except Exception as e:
                rand = "".join(random.choice(string.ascii_lowercase) for _ in range(4))
                instance.slug = slugify(instance.title) + f"-{rand}"
                instance.save()


post_save.connect(recipe_post_save, sender=Recipe)

teacher/recipes/forms.py
from django import forms
from .models import Recipe, Tag, RecipeIngredient
from django.core.exceptions import ValidationError


class RecipeCreateForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['id', 'author', 'title', 'is_active', 'tags']
        exclude = ['slug', 'author']

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 5:
            raise ValidationError('More than 10 letters!')
        if title.capitalize() != title:
            raise ValidationError('First letter should be capital')
        return title

    def __init__(self, *args, **kwargs):
        super(RecipeCreateForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Recipe..',
        })
        self.fields['tags'].widget.attrs.update({
            'class': 'form-control tags'
        })


class RecipeUpdateForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['id', 'author', 'title', 'is_active', 'tags']
        exclude = ['author']

    def __init__(self, *args, **kwargs):
        super(RecipeUpdateForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Recipe..',
        })
        self.fields['is_active'].widget.attrs.update({
            'class': 'form-check-input',
        })
        self.fields['tags'].widget.attrs.update({
            'class': 'form-control tags',
        })


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(TagForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Tag..',
        })


class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = '__all__'
        exclude = ['recipe']

    def __init__(self, *args, **kwargs):
        super(RecipeIngredientForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Ingredient..',
        })
        self.fields['quantity'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['unit'].widget.attrs.update({
            'class': 'form-control',
        })

teacher/recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth.decorators import login_required
from .models import Recipe, RecipeIngredient, Tag
from .forms import RecipeCreateForm, RecipeUpdateForm, TagForm, RecipeIngredientForm
from django.contrib import messages
from django.http import HttpResponse
from django.db.models import Q


def recipe_list(request):
    recipes = Recipe.objects.filter(is_active=True).order_by('-id')
    tags_list = Tag.objects.all()
    q = request.GET.get('q')
    tag = request.GET.get('tag')
    if q:
        recipes = recipes.filter(title__icontains=q)
    if tag:
        recipes = recipes.filter(tags__title=tag)
    ctx = {
        'recipes': recipes,
        'tags_list': tags_list
    }
    return render(request, 'recipes/list.html', ctx)


@login_required
def my_recipes(request):
    user = request.user
    recipes = Recipe.objects.filter(author=user)
    tags_list = Tag.objects.all()
    tag = request.GET.get('tag')
    if tag:
        recipes = recipes.filter(tags__title=tag)
    ctx = {
        "recipes": recipes,
        'tags_list': tags_list
    }
    return render(request, 'recipes/list.html', ctx)


def recipe_detail(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    ctx = {
        "recipe": recipe
    }
    return render(request, 'recipes/detail.html', ctx)


@login_required
def recipe_create(request, *args, **kwargs):
    form = RecipeCreateForm()
    if request.method == 'POST':
        form = RecipeCreateForm(request.POST or None)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author = request.user
            obj.is_active = True
            obj.save()
            form.save_m2m()
            return redirect(reverse("recipes:detail", kwargs={'slug': obj.slug}))
    ctx = {
        'form': form
    }
    return render(request, 'recipes/create.html', ctx)


@login_required
def recipe_update(request, slug):
    obj = get_object_or_404(Recipe, slug=slug)
    if request.user != obj.author:
        if not request.user.is_superuser:
            return HttpResponse("<h1>Hacking with html is funny</h1>")
    form = RecipeUpdateForm(request.POST or None, instance=obj)
    if request.method == 'POST':
        form = RecipeUpdateForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse("recipes:detail", kwargs={"slug": obj.slug}))
    ctx = {
        'form': form
    }
    return render(request, "recipes/update.html", ctx)


@login_required
def recipe_delete(request, slug):
    obj = get_object_or_404(Recipe, slug=slug)
    if request.user != obj.author:
        if not request.user.is_superuser:
            return HttpResponse("<h1>Hacking with html is funny</h1>")
    if request.method == 'POST':
        obj.delete()
        messages.error(request, f"<b>{obj.title}</b> ochirildi")
        return redirect("recipes:list")
    ctx = {
        'object': obj
    }
    return render(request, 'recipes/delete.html', ctx)


def tag_list(request):
    tags = Tag.objects.order_by('id')
    ctx = {
        'object_list': tags
    }
    return render(request, 'recipes/tag/list.html', ctx)


@login_required
def tag_create(request, *args, **kwargs):
    form = TagForm()
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            obj = form.save()
            return redirect(reverse('recipes:tag_detail', kwargs={'pk': obj.id}))
    ctx = {
        'form': form
    }
    return render(request, 'recipes/tag/create.html', ctx)


def tag_detail(request, pk):
    tag = get_object_or_404(Tag, id=pk)
    ctx = {
        'object': tag
    }
    return render(request, 'recipes/tag/detail.html', ctx)


@login_required
def tag_update(request, pk):
    obj = get_object_or_404(Tag, id=pk)
    form = TagForm(instance=obj)
    if request.method == 'POST':
        form = TagForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse('recipes:tag_detail', kwargs={"pk": obj.id}))
    ctx = {
        'form': form
    }
    return render(request, 'recipes/tag/update.html', ctx)


@login_required
def tag_delete(request, pk):
    obj = get_object_or_404(Tag, id=pk)
    if request.method == 'POST':
        obj.delete()
        messages.error(request, f"<b>{obj.title}</b>ochirildi")
        return redirect("recipes:tag_list")
    ctx = {
        "object": obj
    }
    return render(request, "recipes/tag/delete.html", ctx)


@login_required
def ing_create(request, recipe_slug, *args, **kwargs):
    form = RecipeIngredientForm()
    recipe = get_object_or_404(Recipe, slug=recipe_slug)
    if request.user != recipe.author:
        if not request.user.is_superuser:
            return HttpResponse("<h1>Hacking with html is funny</h1>")
    if request.method == 'POST':
        form = RecipeIngredientForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.recipe = recipe
            obj.save()
            return redirect(reverse("recipes:detail", kwargs={"slug": recipe.slug}))
    ctx = {
        'form': form
    }
    return render(request, 'recipes/ing/create.html', ctx)


@login_required
def ing_update(request, recipe_slug, pk):
    obj = get_object_or_404(RecipeIngredient, id=pk)
    recipe = get_object_or_404(Recipe, slug=recipe_slug)
    if request.user != recipe.author:
        if not request.user.is_superuser:
            return HttpResponse("<h1>Hacking with html is funny</h1>")
    form = RecipeIngredientForm(instance=obj)
    if request.method == "POST":
        form = RecipeIngredientForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse("recipes:detail", kwargs={"slug": recipe.slug}))
    ctx = {
        'form': form
    }
    return render(request, 'recipes/ing/update.html', ctx)


@login_required
def ing_delete(request, recipe_slug, pk):
    obj = get_object_or_404(RecipeIngredient, id=pk)
    recipe = get_object_or_404(Recipe, slug=recipe_slug)
    if request.user != recipe.author:
        if not request.user.is_superuser:
            return HttpResponse("<h1>Hacking with html is funny</h1>")
    if request.method == 'POST':
        obj.delete()
        messages.error(request, f"<b>{obj.title}</b> ochirildi")
        return redirect(reverse("recipes:detail", kwargs={"slug": recipe.slug}))
    ctx = {
        'object': obj
    }
    return render(request, 'recipes/ing/delete.html', ctx)

teacher/templates/recipes/create.html
{%extends 'base.html'%}

{%block title%} Recipe create {%endblock%}

{%block content%}
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <form method="post">
          {%csrf_token%}
            <div class="mb-3">
              <label for="title" class="form-label">Title</label>
                <span class="text-danger">{{form.title.errors}}</span>
              {{form.title}}
            </div>
            <div class="mb-3 form-check">
              <label class="form-check-label" for="tags">Tags</label>
              {{form.tags}}
            </div>
            <div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
      </div>
    </div>
  </div>
{%endblock%}

teacher/templates/recipes/delete.html
{%extends 'base.html'%}

{%block title%} Recipe delete {%endblock%}

{%block content%}

<div class="container">
    <form method="post">
        {%csrf_token%}
        <div class="card">
            <div class="card-body color-danger">
                Siz rostanham <strong>{{object.title}}</strong>ni ochirmoqchimisiz?
            </div>
        </div>
        <div class="button-group mt-3">
            <button type="submit" class="btn btn-danger">Xa</button>
            <a href="{%url 'recipes:detail' object.slug%}" class="btn btn-secondary">Yoq</a>
        </div>
    </form>
</div>

{%endblock%}

teacher/templates/recipes/detail.html
{%extends 'base.html'%}

{%block title%} {{recipe.title}} {%endblock%}

{%block content%}

<div class="button-group">
  <a href="{%url 'recipes:list'%}" class="btn btn-dark mb-4 mt-3">Back to recipe list</a>
  <a href="{%url 'recipes:ing_create' recipe.slug%}" class="btn btn-dark mb-4 mt-3 {%if request.user != recipe.author and not request.user.is_superuser%} disabled {%endif%}">Add Ingredient</a>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{recipe.title}}</h5>
    <p class="card-text">{{recipe.author}}</p>
    <div class="button-group mb-3">
      {%for tag in recipe.tags.all%}
        <a href="#" class="btn btn-outline-dark btn-sm">{{tag.title}}</a>
      {%endfor%}
    </div>
    <a href="{%url 'recipes:update' recipe.slug%}" class="btn btn-light {%if request.user != recipe.author and not request.user.is_superuser%} disabled {%endif%}">Edit</a>
    <a href="{%url 'recipes:delete' recipe.slug%}" class="btn btn-danger {%if request.user != recipe.author and not request.user.is_superuser%} disabled {%endif%}">Delete</a>
  </div>
  <div class="card-footer text-muted">
    {{recipe.created_date}}
  </div>
</div>

<div class="row mt-4">
  {%for ingredient in recipe.ingredients.all%}

    <div class="col-sm-6 mb-3 mb-sm-0">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ingredient.title}}</h5>
          <p class="card-text">{{ingredient.quantity}} - {{ingredient.get_unit_display.lower}}</p>
          <a href="{%url 'recipes:ing_update' ingredient.recipe.slug ingredient.id%}" class="btn btn-light {%if request.user != recipe.author and not request.user.is_superuser%} disabled {%endif%}">Edit</a>
          <a href="{%url 'recipes:ing_delete' ingredient.recipe.slug ingredient.id%}" class="btn btn-danger {%if request.user != recipe.author and not request.user.is_superuser%} disabled {%endif%}">Delete</a>
        </div>
        <div class="card-footer text-muted">
          {{ingredient.created_date}}
        </div>
      </div>
    </div>

  {%endfor%}
</div>

{%endblock%}

teacher/templates/recipes/list.html
{%extends 'base.html'%}

{%block title%} Recipe list {%endblock%}

{%block content%}

<div>
    <a href="{%url 'recipes:my_list'%}" class="btn btn-light">My recipes</a>
    <a href="{%url 'recipes:create'%}" class="btn btn-link">Add new recipe</a>
    <a href="{%url 'recipes:tag_create'%}" class="btn btn-link">Add new tag</a>
</div>

<div class="search-div mt-3">
    <form action="{%url 'recipes:list'%}" class="search-form">
        <div class="row g-3 align-items-center">
            <div class="col-auto">
                <input type="search" autocomplete="off" class="form-control" id="exampleFormControlInput2" placeholder="search.." name="q">
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <ol class="list-group list-group-numbered mt-3">
                {%for recipe in recipes%}
                  <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                      <div class="fw-bold {%if not recipe.is_active%} text-danger {%endif%}"><a class="{%if not recipe.is_active%} text-danger {%endif%}" href="{%url 'recipes:detail' recipe.slug%}">{{recipe.title}}</a></div>
                        {{recipe.author}}
                    </div>
                    <span class="badge bg-primary rounded-pill">{{recipe.ingredients.count}}</span>
                  </li>
                {%endfor%}
            </ol>
        </div>
        <div class="col-md-3">
            <div class="button-group">
                <a href="?tag=" class="btn btn-outline-dark btn-sm">All tags</a>
                {%for tag in tags_list%}
                    <a href="?tag={{tag.title}}" class="btn btn-outline-dark btn-sm m-1">{{tag.title}}</a>
                {%endfor%}
            </div>
        </div>
    </div>
</div>
{%endblock%}

teacher/templates/recipes/update.html
{%extends 'base.html'%}

{%block title%} Recipe create {%endblock%}

{%block content%}
<form method="post">
  {%csrf_token%}
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">Title</label>
      {{form.title}}
    </div>
    <div class="mb-3">
      {{form.is_active}}
      <label for="exampleFormControlInput12" class="form-label">Is active</label>
    </div>
    <div class="mb-3 form-check">
      <label class="form-check-label" for="exampleCheck1">Tags</label>
      {{form.tags}}
    </div>
    <div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{%endblock%}