Education/apps/course/urls.py
from django.urls import path, include

app_name = 'course'

urlpatterns = [
    path('', include('apps.course.v1.urls'))
]

Education/apps/course/v1/urls.py
from django.urls import path
from .views import course, CourseDetailView, lesson_detail


urlpatterns = [
    path('', course, name='course'),
    path('detail/<int:pk>/', CourseDetailView.as_view(), name='course-single'),
    path('detail/<int:course_id>/lesson/<int:pk>/', lesson_detail, name='lesson_detail'),
]

Education/apps/main/v1/urls.py
from django.urls import path
from .views import index, about, contact


urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
]

Education/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls', namespace='main')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('account/', include('apps.account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Education/apps/course/models.py
from django.db import models
from apps.main.models import Category, Tag
from apps.account.models import Profile
from ckeditor.fields import RichTextField


class Timestamp(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


def file_path_cover(instance, filename):
    return f"courses/{instance.title}/cover/{filename}"


class Course(Timestamp):
    DIFFICULTY = (
        (0, 'Beginner'),
        (1, 'Intermediate'),
        (2, 'Advanced'),
    )
    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, limit_choices_to={"role": 1})
    title = models.CharField(max_length=221)
    difficulty = models.IntegerField(choices=DIFFICULTY, default=0)
    body = RichTextField()
    cover = models.ImageField(upload_to=file_path_cover, null=True)
    detail_cover = models.ImageField(upload_to=file_path_cover, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True, related_name='course')
    tags = models.ManyToManyField(Tag)
    price = models.DecimalField(decimal_places=2, max_digits=4, null=True, blank=True)
    is_free = models.BooleanField(default=False)
    discount_price = models.DecimalField(decimal_places=2, max_digits=4, null=True, blank=True)

    def __str__(self):
        return self.title


def file_path(instance, filename):
    return f"courses/{instance.lesson.course.title}/{instance.lesson.title}/{filename}"


class Lesson(Timestamp):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=221)
    body = RichTextField()


class LessonFiles(Timestamp):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    file = models.FileField(upload_to=file_path)
    is_main = models.BooleanField(default=False)


class SoldCourse(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

Education/apps/course/v1/views.py
from django.shortcuts import render, redirect, reverse, Http404
from apps.course.models import Course, Lesson, LessonFiles, Category, Tag
from apps.main.v1.forms import SubscribeForm
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, InvalidPage


def course(request):
    courses = Course.objects.all()
    last_three_courses = Course.objects.all()[:3]
    categories = Category.objects.all()
    tags = Tag.objects.all()
    forms = SubscribeForm()
    if request.method == "POST":
        forms = SubscribeForm(data=request.POST)
        if forms.is_valid():
            forms.save()
            return redirect('.')
    page_num = request.GET.get('page')
    paginator = Paginator(courses, 1)
    try:
        page_obj = paginator.page(page_num)
    except EmptyPage:
        page_obj = paginator.page(1)
    except InvalidPage:
        page_obj = paginator.page(1)
    ctx = {
        'courses': page_obj,
        'last_three': last_three_courses,
        'categories': categories,
        'tags': tags,
        'forms': forms
    }
    return render(request, 'course/courses.html', ctx)


class CourseDetailView(generic.View):
    template_name = 'course/course-single.html'
    queryset = Course.objects.all()

    def get_object(self, request, pk):
        try:
            post = self.queryset.get(id=pk)
        except Course.DoesNotExist:
            raise Http404
        return post

    def get_context_data(self, request, pk, **kwargs):
        ctx = {
            'object': self.get_object(request, pk),
            'categories': Category.objects.all(),
            'tags': Tag.objects.all,
            'courses': Course.objects.order_by('-id')[:3],
            'random_courses': Course.objects.order_by('?')[:6]
        }
        return ctx

    def get(self, request, pk, *args, **kwargs):
        ctx = self.get_context_data(request, pk, **kwargs)
        return render(request, self.template_name, ctx)


def lesson_detail(request, course_id, pk):
    lessons = Lesson.objects.get(id=pk)
    course = Course.objects.get(id=course_id)
    lesson_files = LessonFiles.objects.all()
    main_lesson = LessonFiles.objects.filter(lesson_id=pk, is_main=True).first()
    ctx = {
        'lessons': lessons,
        'course': course,
        'main_lesson': main_lesson,
        'lesson_files': lesson_files
    }
    return render(request, 'course/lesson_detail.html', ctx)

Education/templates/course/course-single.html
<!doctype html>
{% load static %}
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/university/course-single.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 23 Feb 2023 14:27:52 GMT -->
<head>
    <title>Free Education Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script nonce="89fafa48-38f3-4108-ad5e-e85a9eb68c9a">
        (function(w,d){!function(f,g,h,i){f[h]=f[h]||{};f[h].executed=[];f.zaraz={deferred:[],listeners:[]};f.zaraz.q=[];f.zaraz._f=function(j){return function(){var k=Array.prototype.slice.call(arguments);f.zaraz.q.push({m:j,a:k})}};for(const l of["track","set","debug"])f.zaraz[l]=f.zaraz._f(l);f.zaraz.init=()=>{var m=g.getElementsByTagName(i)[0],n=g.createElement(i),o=g.getElementsByTagName("title")[0];o&&(f[h].t=g.getElementsByTagName("title")[0].text);f[h].x=Math.random();f[h].w=f.screen.width;f[h].h=f.screen.height;f[h].j=f.innerHeight;f[h].e=f.innerWidth;f[h].l=f.location.href;f[h].r=g.referrer;f[h].k=f.screen.colorDepth;f[h].n=g.characterSet;f[h].o=(new Date).getTimezoneOffset();if(f.dataLayer)for(const s of Object.entries(Object.entries(dataLayer).reduce(((t,u)=>({...t[1],...u[1]})))))zaraz.set(s[0],s[1],{scope:"page"});f[h].q=[];for(;f.zaraz.q.length;){const v=f.zaraz.q.shift();f[h].q.push(v)}n.defer=!0;for(const w of[localStorage,sessionStorage])Object.keys(w||{}).filter((y=>y.startsWith("_zaraz_"))).forEach((x=>{try{f[h]["z_"+x.slice(7)]=JSON.parse(w.getItem(x))}catch{f[h]["z_"+x.slice(7)]=w.getItem(x)}}));n.referrerPolicy="origin";n.src="https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(f[h])));m.parentNode.insertBefore(n,m)};["complete","interactive"].includes(g.readyState)?zaraz.init():f.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document);


    </script>
</head>
<body>

{% include 'header.html' %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
         style="background-image: url({{object.cover.url}});">
    <div class="container">
        <div class="row align-items-center justify-content-center site-hero-sm-inner">
            <div class="col-md-7 text-center">
                <div class="mb-5 element-animate">
                    <h1 class="mb-2">{{object.title}}</h1>
                    <p class="bcrumb"><a href="{% url 'main:index' %}">Home</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <a href="{% url 'course:course' %}">Course</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <span class="current">{{object.title}}</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="site-section bg-light element-animate">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-8 order-md-2 mb-5">
                <div class="row">
                    <div class="col-md-12">
                        <img src="{{object.detail_cover.url}}" alt="" class="img-fluid">
                    </div>
                </div>
                <section class="episodes">
                    <div class="container">
                        <div class="row mb-5">
                            <div class="col-md-12 pt-5">
                                <h2>{{object.title}}</h2>
                                <p>{{object.body|safe}}</p>
                            </div>
                        </div>
                    </div>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 mb-2">
                                <h2>Lesson</h2>
                            </div>
                        </div>
                        {% for lesson in object.lesson_set.all %}
                            <div class="row align-items-center p-4 episode">
                            <div class="col-md-10">
                                <p class="meta">Episode {{forloop.counter}}</p>
                                <h2><a href="{% url 'course:lesson_detail' object.id lesson.id %}">{{lesson.title}}</a></h2>
                                <p>{{lesson.body|safe}}</p>
                            </div>
                            <div class="col-md-2 text-center">
                                <a href="#" class="play"><span class="ion-ios-play"></span></a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </section>
            </div>

            <div class="col-md-6 col-lg-4 order-md-1">
                <div class="block-29 mb-5">
                    <h2 class="heading">Course Details</h2>
                    <ul>
                        <li><span class="text-1">Difficulty: </span> <span class="text-2">{{object.get_difficulty_display}}</span></li>
                        <li><span class="text-1">Lessons: </span> <span class="text-2">{{object.lesson_set.count}}</span></li>
                        <li><span class="text-1">Language: </span> <span class="text-2">English</span></li>
                        <li><span class="text-1">Price: </span> <span class="text-2">{% if course.price %}{{course.price}}{% else %}Free{% endif %}</span></li>
                    </ul>
                </div>
                <div class="block-28 text-center mb-5">
                    <figure>
                        <img src="" alt="" class="img-fluid">
                    </figure>
                    <h2 class="heading">{{object.author}}</h2>
                    <h3 class="subheading">{{object.author.bio}}</h3>
                    <p>
                        <a href="#" class="fa fa-twitter p-2"></a>
                        <a href="#" class="fa fa-facebook p-2"></a>
                        <a href="#" class="fa fa-linkedin p-2"></a>
                    </p>
                    <p>Hi I'm Mark Stewart, consectetur adipisicing elit. Quibusdam nulla beatae modi itaque nemo magni
                        molestiae explicabo sint dolorum cum! Nam iste eligendi autem voluptates illo veritatis veniam
                        laudantium enim!</p>
                </div>
                <div class="block-25 mb-5">
                    <div class="heading">Recent Courses</div>
                    <ul>
                        {% for course in courses %}
                            <li>
                            <a href="#" class="d-flex">
                                <figure class="image mr-3">
                                    <img src="{{course.cover.url}}" alt="" class="img-fluid">
                                </figure>
                                <div class="text">
                                    <h3 class="heading">{{course.title}}</h3>
                                    <span class="meta">
                                        {% if course.price %}
                                            {{course.price}}
                                        {% else %}
                                            Free
                                        {% endif %}
                                    </span>
                                </div>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="block-24 mb-5">
                    <h3 class="heading">Categories</h3>
                    <ul>
                        {% for cat in categories %}
                            <li><a href="{% url 'course:course' %}?cat={{cat.title}}">{{cat.title}} <span>{{cat.post.count}}</span></a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="block-26">
                    <h3 class="heading">Tags</h3>
                    <ul>
                        {% for tag in tags %}
                            <li><a href="{% url 'course:course' %}?tag={{tag.title}}">{{tag.title}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row justify-content-center mb-5 element-animate">
            <div class="col-md-7 text-left section-heading">
                <h2 class="text-primary heading">You May Also Like</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit qui neque sint eveniet tempore
                    sapiente.</p>
            </div>
        </div>
    </div>
    <div class="container-fluid block-11 element-animate">
        <div class="nonloop-block-11 owl-carousel">
            {% for random in random_courses %}
                <div class="item">
                <div class="block-19">
                    <figure>
                        <img src="{{random.cover.url}}" alt="Image" class="img-fluid">
                    </figure>
                    <div class="text">
                        <h2 class="heading"><a href="{% url 'course:course-single' random.id %}">{{random.title}}</a></h2>
                        <p class="mb-4">{{random.body|safe|slice:100}}</p>
                        <div class="meta d-flex align-items-center">
                            <div class="number">
                                <span>2,219/6,000</span>
                            </div>
                            <div class="price text-right">
                                <del class="mr-3">{{random.price}}</del>
                                <span>Free</span></div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>

<div class="py-5 block-22">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 mb-4 mb-md-0 pr-md-5">
                <h2 class="heading">Create cool websites</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi accusantium optio und.</p>
            </div>
            <div class="col-md-6">
                <form action="#" class="subscribe">
                    <div class="form-group">
                        <input type="email" class="form-control email" placeholder="Enter email">
                        <input type="submit" class="btn btn-primary submit" value="Subscribe">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% include 'footer.html' %}

<div id="loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#f4b214"/>
    </svg>
</div>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');


</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993"
        integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA=="
        data-cf-beacon='{"rayId":"79e0a4bbbd88fe40","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2023.2.0","si":100}'
        crossorigin="anonymous"></script>
</body>

</html>

Education/templates/course/courses.html
<!doctype html>
{% load static %}
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/university/courses.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 23 Feb 2023 14:27:49 GMT -->
<head>
    <title>Free Education Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script nonce="2fdba83f-ef72-46c7-833b-6beb353a2503">
        (function(w,d){!function(f,g,h,i){f[h]=f[h]||{};f[h].executed=[];f.zaraz={deferred:[],listeners:[]};f.zaraz.q=[];f.zaraz._f=function(j){return function(){var k=Array.prototype.slice.call(arguments);f.zaraz.q.push({m:j,a:k})}};for(const l of["track","set","debug"])f.zaraz[l]=f.zaraz._f(l);f.zaraz.init=()=>{var m=g.getElementsByTagName(i)[0],n=g.createElement(i),o=g.getElementsByTagName("title")[0];o&&(f[h].t=g.getElementsByTagName("title")[0].text);f[h].x=Math.random();f[h].w=f.screen.width;f[h].h=f.screen.height;f[h].j=f.innerHeight;f[h].e=f.innerWidth;f[h].l=f.location.href;f[h].r=g.referrer;f[h].k=f.screen.colorDepth;f[h].n=g.characterSet;f[h].o=(new Date).getTimezoneOffset();if(f.dataLayer)for(const s of Object.entries(Object.entries(dataLayer).reduce(((t,u)=>({...t[1],...u[1]})))))zaraz.set(s[0],s[1],{scope:"page"});f[h].q=[];for(;f.zaraz.q.length;){const v=f.zaraz.q.shift();f[h].q.push(v)}n.defer=!0;for(const w of[localStorage,sessionStorage])Object.keys(w||{}).filter((y=>y.startsWith("_zaraz_"))).forEach((x=>{try{f[h]["z_"+x.slice(7)]=JSON.parse(w.getItem(x))}catch{f[h]["z_"+x.slice(7)]=w.getItem(x)}}));n.referrerPolicy="origin";n.src="https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(f[h])));m.parentNode.insertBefore(n,m)};["complete","interactive"].includes(g.readyState)?zaraz.init():f.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document);


    </script>
</head>
<body>

{% include 'header.html' %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
         style="background-image: url({% static 'images/big_image_2.jpg' %});">
    <div class="container">
        <div class="row align-items-center justify-content-center site-hero-sm-inner">
            <div class="col-md-7 text-center">
                <div class="mb-5 element-animate">
                    <h1 class="mb-2">Courses</h1>
                    <p class="bcrumb"><a href="{% url 'main:index' %}">Home</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <span class="current">Courses</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-8 order-md-2">
                <div class="row">
                    {% for course in courses %}
                    <div class="col-md-12 col-lg-6 mb-5">
                        <div class="block-19">
                            <figure>
                                <a href="{% url 'course:course-single' course.id %}"><img src="{{course.cover.url}}"
                                                                                          alt="Image"
                                                                                          class="img-fluid"></a>
                            </figure>
                            <div class="text">
                                <h2 class="heading"><a href="{% url 'course:course-single' course.id %}">{{course.title|safe}}</a>
                                </h2>
                                <p class="mb-4">{{course.body|safe|slice:75}}</p>
                                <div class="meta d-flex align-items-center">
                                    <div class="number">
                                        <span>{{course.soldcourse_set.count}}</span>
                                    </div>
                                    <div class="price text-right">
                                        <del class="mr-3">
                                        </del>
                                        <span>
                                            {% if course.price %}
                                                ${{course.price}}
                                            {% else %}
                                                Free
                                            {% endif %}</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="row mb-5">
                    <div class="col-md-12 text-center">
                        <div class="block-27">
                            <ul>
                                {% if courses.has_previous %}
                                    <li><a href="?page={{courses.previous_page_number}}">&lt;</a></li>
                                {% endif %}
                                {% for page in courses.paginator.page_range%}
                                    <li class="{% if page == courses.number %}active{%endif %}"><span><a href="?page={{page}}">{{page}}</a></span></li>
                                {% endfor %}
                                {% if courses.has_next %}
                                    <li><a href="?page={{courses.next_page_number}}">&gt;</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-lg-4 order-md-1">
                <div class="block-24 mb-5">
                    <h3 class="heading">Categories</h3>
                    <ul>
                        {% for cat in categories %}
                        <li><a href="#">{{cat.title}} <span>{{cat.course.count}}</span></a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="block-25 mb-5">
                    <div class="heading">Recent Courses</div>
                    <ul>
                        {% for last in last_three %}
                        <li>
                            <a href="{% url 'course:course-single' last.id %}" class="d-flex">
                                <figure class="image mr-3">
                                    <img src="{{last.cover.url}}" alt="" class="img-fluid">
                                </figure>
                                <div class="text">
                                    <h3 class="heading">{{last.title}}</h3>
                                    <span class="meta">
                                        {% if last.price %}
                                            {{last.price}}
                                        {% else %}
                                            Free
                                        {% endif %}
                                    </span>
                                </div>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="block-26">
                    <h3 class="heading">Tags</h3>
                    <ul>
                        {% for tag in tags %}
                        <li><a href="#">{{tag.title}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="py-5 block-22">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 mb-4 mb-md-0 pr-md-5">
                <h2 class="heading">Create cool websites</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi accusantium optio und.</p>
            </div>
            <div class="col-md-6">
                <form method="post" class="subscribe">
                    {%csrf_token%}
                    <div class="form-group">
                        {{forms.email}}
                        <input type="submit" class="btn btn-primary submit" value="Subscribe">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% include 'footer.html' %}

<div id="loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#f4b214"/>
    </svg>
</div>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');



</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993"
        integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA=="
        data-cf-beacon='{"rayId":"79e0a3af0c6f3769","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2023.2.0","si":100}'
        crossorigin="anonymous"></script>
</body>

</html>