music_site/blog/urls.py
from django.urls import path
from .views import index, archive, detail

app_name = 'blog'

urlpatterns = [
    path('', index, name='index'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('archive/<int:pk>/', archive, name='archive'),
]

music_site/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('podcast/', include('podcast.urls', namespace='podcast')),
    path('about/', include('about.urls', namespace='about')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('account/', include('profiles.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music_site/podcast/urls.py
from django.urls import path
from .views import index, list, detail, archive, like, ids_list

app_name = 'podcast'

urlpatterns = [
    path('', index, name='index'),
    path('list/', list, name='list'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('like/', like, name='like'),
    path('ids_list/', ids_list, name='ids_list'),
    path('archive/<int:pk>', archive, name='archive'),
]

music_site/profiles/urls.py
from django.urls import path
from .views import login_view, logout_view, register_view

app_name = 'account'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
]

music_site/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">

<head>
    <title>My Podcast</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="My Podcast template project">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{%static 'styles/bootstrap-4.1.2/bootstrap.min.css'%}">
    <link href="{%static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css">
    <link href="{%static 'plugins/colorbox/colorbox.css'%}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{%static 'styles/main_styles.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'styles/responsive.css'%}">
    {% block css %}

    {% endblock %}
    <script nonce="c121fd35-08cf-4544-9d26-9241b250b23a">
        (function(w,d){!function(f,g,h,i){f[h]=f[h]||{};f[h].executed=[];f.zaraz={deferred:[],listeners:[]};f.zaraz.q=[];f.zaraz._f=function(j){return function(){var k=Array.prototype.slice.call(arguments);f.zaraz.q.push({m:j,a:k})}};for(const l of["track","set","debug"])f.zaraz[l]=f.zaraz._f(l);f.zaraz.init=()=>{var m=g.getElementsByTagName(i)[0],n=g.createElement(i),o=g.getElementsByTagName("title")[0];o&&(f[h].t=g.getElementsByTagName("title")[0].text);f[h].x=Math.random();f[h].w=f.screen.width;f[h].h=f.screen.height;f[h].j=f.innerHeight;f[h].e=f.innerWidth;f[h].l=f.location.href;f[h].r=g.referrer;f[h].k=f.screen.colorDepth;f[h].n=g.characterSet;f[h].o=(new Date).getTimezoneOffset();if(f.dataLayer)for(const s of Object.entries(Object.entries(dataLayer).reduce(((t,u)=>({...t[1],...u[1]})))))zaraz.set(s[0],s[1],{scope:"page"});f[h].q=[];for(;f.zaraz.q.length;){const v=f.zaraz.q.shift();f[h].q.push(v)}n.defer=!0;for(const w of[localStorage,sessionStorage])Object.keys(w||{}).filter((y=>y.startsWith("_zaraz_"))).forEach((x=>{try{f[h]["z_"+x.slice(7)]=JSON.parse(w.getItem(x))}catch{f[h]["z_"+x.slice(7)]=w.getItem(x)}}));n.referrerPolicy="origin";n.src="https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(f[h])));m.parentNode.insertBefore(n,m)};["complete","interactive"].includes(g.readyState)?zaraz.init():f.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document);




    </script>
</head>
<body>
<div class="super_container">

    {%include 'header.html'%}

    {%block content%}

    {%endblock%}

    {%include 'footer.html'%}

</div>
<script src="{%static 'js/jquery-3.3.1.min.js'%}"></script>
<script src="{%static 'styles/bootstrap-4.1.2/popper.js'%}"></script>
<script src="{%static 'styles/bootstrap-4.1.2/bootstrap.min.js'%}"></script>
<script src="{%static 'plugins/greensock/TweenMax.min.js'%}"></script>
<script src="{%static 'plugins/greensock/TimelineMax.min.js'%}"></script>
<script src="{%static 'plugins/scrollmagic/ScrollMagic.min.js'%}"></script>
<script src="{%static 'plugins/greensock/animation.gsap.min.js'%}"></script>
<script src="{%static 'plugins/greensock/ScrollToPlugin.min.js'%}"></script>
<script src="{%static 'plugins/easing/easing.js'%}"></script>
<script src="{%static 'plugins/colorbox/jquery.colorbox-min.js'%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jplayer/2.9.2/jplayer/jquery.jplayer.min.js"
        integrity="sha512-g0etrk7svX8WYBp+ZDIqeenmkxQSXjRDTr08ie37rVFc99iXFGxmD0/SCt3kZ6sDNmr8sR0ISHkSAc/M8rQBqg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jplayer/2.9.2/add-on/jplayer.playlist.min.js"
        integrity="sha512-URFV3t5uXfvKOagAfyhVvwKvilA4QPsnyCAd4I7GHPer6eipGwz/1l/XLvjNMc4CUz1LDvIqYqQV/YZE9Uf7Hg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{%static 'plugins/progressbar/progressbar.min.js'%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js"
        integrity="sha512-Zq2BOxyhvnRFXu0+WE6ojpZLOU2jdnqbrM1hmVdGzyeCa1DgM3X5Q4A/Is9xA1IkbUeDd7755dNNI/PzSf2Pew=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{%static 'plugins/parallax-js-master/parallax.min.js'%}"></script>
<script src="{%static 'js/custom.js'%}"></script>
{% block js %}

{% endblock %}

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');





</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993"
        integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA=="
        data-cf-beacon='{"rayId":"794a66361a96d93f","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2022.11.3","si":100}'
        crossorigin="anonymous"></script>

<script>


    $('.do_like').on('click', function () {
        let music_id = $(this).data('music_id');
        $.ajax({
            url: "http://127.0.0.1:8000/podcast/like/",
            type: 'POST',
            dataType: 'json',
            data: {
                "music_id": music_id
            },
            success: function (res) {
                var lcount = $(`#lcount_${music_id}`).text();
                if(!$(`#lbtn_${music_id}`).hasClass("liked")){
                    $(`#lcount_${music_id}`).text(parseInt(lcount)+1);
                    $(`#lbtn_${music_id}`).addClass('liked');
                    $(`#lbtn_${music_id}`).addClass('active');
                } else {
                    $(`#lcount_${music_id}`).text(parseInt(lcount)-1);
                    $(`#lbtn_${music_id}`).removeClass('liked');
                    $(`#lbtn_${music_id}`).removeClass('active');
                }

            }
        });

    });


</script>
</body>

<!-- Mirrored from preview.colorlib.com/theme/mypodcast/ by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 05 Feb 2023 08:51:22 GMT -->
</html>

music_site/templates/footer.html
{%load static%}
<footer class="footer">
    <div class="container">
        <div class="row footer_logo_row">
            <div class="col d-flex flex-row align-items-center justify-content-center">
                <div class="logo">
                    <a href="{%url 'podcast:index'%}"><span>my</span>podcast<img src="images/play.png" alt=""></a>
                </div>
            </div>
        </div>
        <div class="row footer_content_row">

            <div class="col-lg-4">
                <div class="footer_title">Tags</div>
                <div class="footer_list">
                    {% for tag in tagsf %}
                    <div>
                        <div><a href="#">{{tag.title}}</a></div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="col-lg-4">
                <div class="footer_title">Latest Episodes</div>
                <div class="latest_container">
                    {%for object in object_listf %}
                    <div class="latest">
                        <div class="latest_title_container d-flex flex-row align-items-start justify-content-start">
                            <a href="{%url 'podcast:detail' object.id %}">
                                <div class="d-flex flex-row align-items-start justify-content-start">
                                    <div class="latest_play">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1"
                                             x="0px" y="0px" width="512px" height="512px" viewBox="0 0 714 714"
                                             style="enable-background:new 0 0 714 714;" xml:space="preserve">
<g id="Play">
<path d="M641.045,318.521L102,0C73.822,0,51,22.822,51,51v612c0,28.178,22.822,51,51,51l539.045-318.521      C654.661,387.422,663,372.81,663,357C663,341.19,654.661,326.579,641.045,318.521z M153,565.386V148.614L505.665,357      L153,565.386z"
      fill="#FFFFFF"/>
</g>
</svg>
                                    </div>
                                    <div class="latest_title_content">
                                        <div class="latest_title">Season {{object.season.id}} - {{object.title}}</div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="latest_episode_info">
                            <ul class="d-flex flex-row align-items-start justify-content-start">
                                <li><a href="#">{{object.created_date|date:"F Y"}}</a></li>
                                <li><a href="#">{{object.category.title}}</a></li>
                            </ul>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="col-lg-4">
                <div class="footer_title">Blogs</div>
                <div class="gallery d-flex flex-row align-items-start justify-content-start flex-wrap">
                    {% for blog in blogs %}
                    <div class="gallery_item">
                        <a class="colorbox" href="{{blog.image.url}}"><img src="{{blog.image.url}}"
                                                                             alt=""></a>
                    </div>
                    {%endfor%}
                </div>
            </div>
        </div>
        <div class="row footer_social_row">
            <div class="col">
                <div class="footer_social">
                    <ul class="d-flex flex-row align-items-center justify-content-center">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-soundcloud" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
        </br></br>
        Copyright &copy;<script>document.write(new Date().getFullYear());</script>
        All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
            href="https://colorlib.com/" target="_blank">Colorlib</a>

    </div>
</footer>

music_site/templates/header.html
{%load static%}
<header class="header trans_400">

    <div class="logo">
        <a href="{%url 'podcast:index'%}"><span>my</span>podcast<img src="images/play.png" alt=""></a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="header_content d-flex flex-row align-items-center justify-content-start trans_400">
                    <nav class="main_nav">
                        <ul class="d-flex flex-row align-items-start justify-content-start">
                            <li><a href="{%url 'podcast:index'%}">Home</a></li>
                            <li><a href="{%url 'about:index'%}">About</a></li>
                            <li><a href="{%url 'podcast:list'%}">Episodes</a></li>
                            <li><a href="{%url 'blog:index'%}">Blog</a></li>
                            <li><a href="{%url 'contact:index'%}">Contact</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="header_right d-flex flex-row align-items-start justify-content-start">
        {%if request.user.is_authenticated%}
            <div class="submit"><a href="#">{{request.user.profile}}</a></div>
            <div class="submit"><a href="{%url 'account:logout'%}">Logout</a></div>
        {%else%}
            <div class="submit"><a href="{%url 'account:login'%}">Login</a></div>
        {%endif%}
        <div class="hamburger"><i class="fa fa-bars" aria-hidden="true"></i></div>
    </div>
</header>

music_site/templates/pagination.html
<ul class="pagination">
{% if object_list.has_previous %}
    <li><a class="fa fa-angle-double-left" href="?page={{object_list.previous_page_number}}"></a></li>
{% endif %}
{% for page in object_list.paginator.page_range %}
    <li class="{% if page == object_list.number %}active{% endif %}"><a href="?page={{page}}">{{page}}</a></li>
{%endfor%}
{% if object_list.has_next %}
    <li><a class="fa fa-angle-double-right" href="?page={{object_list.next_page_number}}"></a></li>
{% endif %}
</ul>